language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: nQ42kaa6bNTkz2VCfE2Z4+TJJIlGD0Swn+GzeDtLZC1eErmXpyNdqNvGZp9OKjgecQJkK4ZaQ7ZxbZJQEpouVmKW3snZjYQOTmtVsMyUjHegp6dFFqeBj6v3DEvuBAd/I93vdMGdIzLLp/HMYJvx/17oTcQTcS2PKme/yV8u9aUw6l6CiamYCBAPDskMowUdj8SJHLiZEXtuaR5M0zwPK2MJEV2LkEYJGNUyZ/pqP5+54yij1DtjVNX9p3aOgk1hD8fD9q1T48V/6UiXcwpaERRlGkpaB4gD5tCR+T/36WqEPyAeRAJRPdytnHAMMVbEobQPuQAbTkFpkz6AZI9jsklkGKJgZrRz9GNOD0bhk4AvOT/rbQNS5koROFxh83TIHAytoRYzP4Do7cQx82jSmzwvfEYUXvhlLvY+7Gq3ZHuT2OT6G5pG/s8rZfoouaLHOGQM6xfn6ok94LDPryEaHE4egrQdobgC0I4CecQJAFVzJIPz4zzAffJyI0bc8H4mwTcNgsn4oHhpvuyzssz/+uvgaHXDHE3k8vfZpBp15cY1R10Cd1kQ5vXnzs5iP/vlerRV30y7dTlqjg5r76jk1cLYZUc/0tJlbYgYY+dFhBYjSkLqHF7rbs+bQ3QZNgUfyY3kWdsYZM8md+WvXZWUEpTYpLoMZYSwsDsH0uGlrFo=
  - secure: aIuDbo1ILXQ0P3axQOFZSVJyKR09s2S40fy8QrONVdhfA7hS52fZUf3hruoS2Uof+2bRyTC3UVk52VgxpDDdCS/8PWgtogj4m3lnjEqfyyZALI6XhpgNXT/G5LNNonpcUA0dOUfLJ3mQNrBqUegW7jABfWqDfXe6UxP+qaSXKQjRQ5Otc12xVk8rFJrkyi+dWyMjwY0HJdRmxXKjKts2cD9d3EccmkKP/Y+f9FLHAcTYmzM080irQ5BOT21K032gMY0B6z4OCKfjTGzY82UpzO/09CFCR1tEV+eeUyECHEkHKl6CfoQ6PQdwf1WKnZL1Jdyk7vHbRgkLe2gjJLpUFHVIUd1P2JIhR9/OauD2k5LMR5brLtJqIqNiqmGCrznuessIx0UKU04PQ+7G8NxSJKTeq6hGQdzQn5lHc75cEp1/GsqmEEaFqACGgtLVo66jG8AcP043H5OZyyjSQg90+zIYkqHtlVL3aGIhb+HXDqbK4bQBzB4SoE6IOAWoDLWCIrzD/sS+GWy3LFUWfwtlUfKkz40d1GkR8VNOKp3ATrF1iWeW5G/0oxK/Aa/Rpcv5KIg2O0stOApHTDLsU8jgQOs8zfnP639kYICgD2NYqNTF0SYrMF6myQp0hE1q5L6Ds7yBkQYR68Vam/6Csl2/f4SmPIStJNeBxh+FYl9iuAs=
